  ##Role for installing Argocd 
---
  - name: creating the namespace 
    command: kubectl create namespace argocd 

  - name: Applying the repo 
    command: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

  - name: exposing the server 
    command: kubectl expose svc argocd-server -n argocd --type=NodePort --port=8080 --name=argocd-new-server

  - name: Accessing the argocd-new-server
    command: "kubectl get service/argocd-new-server -n argocd"
    register: service_value

 
    
  - name: adding the value in file
    command: "echo {{ service_value.stdout }} >> /tmp/argocd-server"

  - name: filtering the output to port
    shell: cat /tmp/argocd-server | awk 'NR==2 {print $5}'
    register: port_value

  - name:  getting the hostname 
    shell: "hostname -I | awk '{print $1}'"
    register: host_ip

  # - name: displaying the service_vlalue
  #   debug: 
  #     msg: "{{ host_ip.stdout }}"

  # - name: displaying the service_vlalue
  #   debug: 
  #     msg: "{{ port_value.stdout }}"

  - name: printing the url for acccessing the argocd UI
    debug: 
      msg: "hostIP:{{host_ip.stdout}}  Port:{{port_value.stdout}}"


