  ##Role for installing Argocd 
---
  - name: creating the namespace 
    comamd: kubectl create namespace argocd 

  - name: Applying the repo 
    comamd: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

  - name: exposing the server 
    comamd: kubectl expose svc argocd-server -n argocd --type=NodePort --port=8080 --name=argocd-new-server

  - name: Accessing the argocd-new-server
    command: kubectl get svc argocd-new-server -n argocd 

  - name: filtering the output to port
    command: awk '{split($5, a, ":"); split(a[2], b, "/"); print b[1]}'
    register: port_value

  - name:  getting the hostname 
    command: hostname -I | awk '{print $1}'
    reagister: host_ip

  - name: printing the url for acccessing the argocd UI
    debug: 
      msg: "{{host_ip}}:{{port_value}}"


